FROM {{ dist }}:{{ release }}
MAINTAINER {{ maintainer }}
COPY /etc/environment /etc/environment
COPY /etc/apt/apt.conf.d/*proxy /etc/apt/apt.conf.d/90proxy
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y dpkg-dev aptitude build-essential ; mkdir -p /usr/lib/pbuilder/
COPY scripts/pbuilder-satisfydepends* /usr/lib/pbuilder/
